### Array Attributes in NumPy  
**Author:** Taskeen Hussain  

Array attributes in NumPy provide essential metadata about arrays, such as their shape, size, dimensionality, and data type. These attributes help you understand and manipulate arrays effectively for numerical and scientific computing tasks.

In [4]:
import numpy as np 
a = np.array([[1,2,3,5,7],[4,5,6,8,9]]) 
print (a.shape)

(2, 5)


In [6]:
a = np.array([[1,2,3,5,7],[4,5,6,8,9]]) 
a.shape = (5,2) 
print (a)

[[1 2]
 [3 5]
 [7 4]
 [5 6]
 [8 9]]


In [10]:
a = np.array([[1,2,3,5,7],[4,5,6,8,9]]) 
b = a.reshape(5,2) 
print (b)

[[1 2]
 [3 5]
 [7 4]
 [5 6]
 [8 9]]


In [11]:
a = np.arange(24) 
a.ndim  


1

In [12]:
# an array of evenly spaced numbers 
import numpy as np 
a = np.arange(24) 
print (a)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [13]:
# now reshape it 
b = a.reshape(2,4,3) 
print (b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [14]:
# dtype of array is int8 (1 byte) 
import numpy as np 
x = np.array([1,2,3,4,5], dtype = np.int8) 
print (x.itemsize)

1


In [15]:
# dtype of array is now float32 (4 bytes) 
import numpy as np 
x = np.array([1,2,3,4,5], dtype = np.float32) 
print (x.itemsize)

4


In [16]:
x = np.array([1,2,3,4,5]) 
print (x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [17]:
x = np.empty([3,2], dtype = int) 
print (x)

[[1 2]
 [3 4]
 [5 6]]


In [18]:
# array of five zeros. Default dtype is float 
import numpy as np 
x = np.zeros(5) 
print (x)

[0. 0. 0. 0. 0.]


In [22]:
import numpy as np
x = np.zeros((5, 2), dtype=int)  # Use `int` instead of `np.int`
print(x)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [23]:
import numpy as np
x = np.zeros((5,), dtype=int)  # Use `int` instead of `np.int`
print(x)

[0 0 0 0 0]


In [20]:
# custom type 
import numpy as np 
x = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print (x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [24]:
# array of five ones. Default dtype is float 
import numpy as np 
x = np.ones(5) 
print (x)

[1. 1. 1. 1. 1.]


In [25]:
x = np.ones([2,2], dtype = int) 
print (x)

[[1 1]
 [1 1]]
