### Array From Existing Data in NumPy  
**Author:** Taskeen Hussain  

#### NumPy allows creating arrays from existing data structures such as lists, tuples, or buffers. This feature enables seamless data conversion and manipulation for efficient numerical computations.

In [3]:
# convert list to ndarray 
import numpy as np 

x = [1,2,3] 
a = np.asarray(x) 
print (a)

[1 2 3]


In [4]:
# dtype is set 
import numpy as np 

x = [1,2,3]
a = np.asarray(x, dtype = float) 
print (a)

[1. 2. 3.]


In [5]:
# ndarray from tuple 
import numpy as np 

x = (1,2,3) 
a = np.asarray(x) 
print (a)

[1 2 3]


In [7]:
# ndarray from list of tuples 
import numpy as np 

x = [(1,2,3),(4,5,6)] 
a = np.asarray(x) 
print (a)

[[1 2 3]
 [4 5 6]]


In [8]:
# obtain iterator object from list 
import numpy as np 
list = range(5) 
it = iter(list)  

In [9]:
# use iterator to create ndarray 
x = np.fromiter(it, dtype = float) 
print (x)

[0. 1. 2. 3. 4.]


In [10]:
x = np.arange(5) 
print (x)

[0 1 2 3 4]


In [11]:
# dtype set 
x = np.arange(5, dtype = float)
print (x)

[0. 1. 2. 3. 4.]


In [12]:
# start and stop parameters set 
import numpy as np 
x = np.arange(10,20,2) 
print (x)

[10 12 14 16 18]


In [13]:
x = np.linspace(10,20,5) 
print (x)

[10.  12.5 15.  17.5 20. ]


In [14]:
# endpoint set to false 
import numpy as np 
x = np.linspace(10,20, 5, endpoint = False) 
print (x)

[10. 12. 14. 16. 18.]


In [15]:
# endpoint set to true 
import numpy as np 
x = np.linspace(10,20, 5, endpoint = True) 
print (x)

[10.  12.5 15.  17.5 20. ]


In [16]:
# find retstep value 
import numpy as np 

x = np.linspace(1,2,5, retstep = True) 
print (x) 

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), np.float64(0.25))


In [17]:
# find retstep value 
import numpy as np 

x = np.linspace(1,2,5, retstep = False) 
print (x) 

[1.   1.25 1.5  1.75 2.  ]


In [18]:
# default base is 10 
a = np.logspace(1.0, 2.0, num = 10) 
print (a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [20]:
# set base of log space to 2 
import numpy as np 
a = np.logspace(1,10,num = 10, base = 2) 
print (a)

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]
