### Indexing & Slicing in NumPy  
**Author:** Taskeen Hussain  

#### Indexing and slicing in NumPy allow efficient access and manipulation of array elements. These techniques help extract specific data subsets, modify arrays, and perform advanced operations seamlessly.

In [2]:
import numpy as np 
a = np.arange(10) 
s = slice(2,7,2) 
print (a[s])

[2 4 6]


In [3]:
import numpy as np 
a = np.arange(10) 
b = a[2:7:2] 
print (b)

[2 4 6]


In [4]:
# slice single item 
import numpy as np 

a = np.arange(10) 
b = a[5] 
print (b)

5


In [5]:
# slice items starting from index 
import numpy as np 
a = np.arange(10) 
print (a[2:])

[2 3 4 5 6 7 8 9]


In [6]:
# slice items between indexes 
import numpy as np 
a = np.arange(10) 
print (a[2:5])

[2 3 4]


In [7]:
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a)

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [8]:
# slice items starting from index
print ('Now we will slice the array from the index a[1:]') 
print (a[1:])

Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]


In [9]:
# array to begin with 
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]])

In [10]:
print ('Our array is:') 
print (a) 
print ('\n')

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]




In [11]:
# this returns array of items in the second column 
print ('The items in the second column are:')  
print (a[...,1]) 
print ('\n')

The items in the second column are:
[2 4 5]




In [14]:
# Now we will slice all items from the second row 
print ('The items in the second row are:') 
print (a[1,...])
print ('\n')

The items in the second row are:
[3 4 5]




In [13]:
# Now we will slice all items from column 1 onwards 
print ('The items column 1 onwards are:')
print (a[...,1:])

The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]


In [15]:
# ### Integer Indexing
# 

# ### Example 1
# 

# In[9]:


import numpy as np 

x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
print (y)

[1 4 5]


In [16]:
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
   
print ('Our array is:') 
print (x) 
print ('\n') 

rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols] 
   
print ('The corner elements of this array are:')
print (y)

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The corner elements of this array are:
[[ 0  2]
 [ 9 11]]


In [17]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

print ('Our array is:') 
print (x) 
print ('\n')  

# slicing 
z = x[1:4,1:3] 

print ('After slicing, our array becomes:') 
print (z) 
print ('\n')  

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


After slicing, our array becomes:
[[ 4  5]
 [ 7  8]
 [10 11]]




In [18]:
# using advanced index for column 
y = x[1:4,[1,2]] 

print ('Slicing using advanced index for column:') 
print (y)

Slicing using advanced index for column:
[[ 4  5]
 [ 7  8]
 [10 11]]


In [19]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

print ('Our array is:') 
print (x) 
print ('\n')  

# Now we will print the items greater than 5 
print ('The items greater than 5 are:') 
print (x[x > 5])

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The items greater than 5 are:
[ 6  7  8  9 10 11]


In [20]:
a = np.array([np.nan, 1,2,np.nan,3,4,5]) 
print (a[~np.isnan(a)])

[1. 2. 3. 4. 5.]


In [21]:
a = np.array([1, 2+6j, 5, 3.5+5j]) 
print (a[np.iscomplex(a)])

[2. +6.j 3.5+5.j]
