### Broadcasting in NumPy  
**Author:** Taskeen Hussain  

#### Broadcasting in NumPy allows arrays of different shapes to be used in arithmetic operations. It automatically expands the smaller array to match the larger one, enabling efficient element-wise operations without the need for explicit looping.

In [2]:
import numpy as np 
a = np.array([1,2,3,4])  
b = np.array([10,20,30,40])  
c = a * b  
print (c)

[ 10  40  90 160]


In [3]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print ('First array:') 
print (a) 
print ('\n')  
   
print ('Second array:') 
print (b) 
print ('\n')  
   
print ('First Array + Second Array') 
print (a + b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [5]:
# ## Iterating Over Array

import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)

print ('Original array is:')
print (a)
print ('\n')

print ('Modified array is:')
for x in np.nditer(a):
 print(x)


Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55


In [6]:
a = np.arange(0,60,5) 
a = a.reshape(3,4) 
   
print ('Original array is:')
print (a) 
print ('\n')  
   
print ('Transpose of the original array is:') 
b = a.T 
print (b) 
print ('\n')  
   
print ('Modified array is:') 
for x in np.nditer(b): 
   print (x)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Transpose of the original array is:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55


In [7]:
a = np.arange(0,60,5)
a = a.reshape(3,4)
print ('Original array is:')
print (a)
print ('\n')

print ('Transpose of the original array is:')
b = a.T
print (b)
print ('\n')

print ('Sorted in C-style order:')
c = b.copy(order = 'C')
print (c)
for x in np.nditer(c):
   print (x)

print ('\n')

print ('Sorted in F-style order:')
c = b.copy(order = 'F')
print (c)
for x in np.nditer(c):
   print (x)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Transpose of the original array is:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


Sorted in C-style order:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
20
40
5
25
45
10
30
50
15
35
55


Sorted in F-style order:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
5
10
15
20
25
30
35
40
45
50
55


In [8]:
a = np.arange(0,60,5) 
a = a.reshape(3,4) 

print ('Original array is:') 
print (a) 
print ('\n')  

print ('Sorted in C-style order:') 
for x in np.nditer(a, order = 'C'): 
   print (x)  
print ('\n') 

print ('Sorted in F-style order:') 
for x in np.nditer(a, order = 'F'): 
   print (x)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Sorted in C-style order:
0
5
10
15
20
25
30
35
40
45
50
55


Sorted in F-style order:
0
20
40
5
25
45
10
30
50
15
35
55


In [9]:
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)
print ('Original array is:')
print (a)
print ('\n')

for x in np.nditer(a, op_flags = ['readwrite']):
   x[...] = 2*x
print ('Modified array is:')
print (a)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


In [10]:
a = np.arange(0,60,5) 
a = a.reshape(3,4) 

print ('Original array is:') 
print (a) 
print ('\n')  

print ('Modified array is:') 
for x in np.nditer(a, flags = ['external_loop'], order = 'F'):
   print (x)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
[ 0 20 40]
[ 5 25 45]
[10 30 50]
[15 35 55]


In [11]:
# ### Broadcasting Iteration

import numpy as np 
a = np.arange(0,60,5) 
a = a.reshape(3,4) 

print ('First array is:') 
print (a) 
print ('\n')  

print ('Second array is:') 
b = np.array([1, 2, 3, 4], dtype = int) 
print (b)  
print ('\n') 

print ('Modified array is:') 
for x,y in np.nditer([a,b]): 
   print ("%d:%d" % (x,y))

First array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Second array is:
[1 2 3 4]


Modified array is:
0:1
5:2
10:3
15:4
20:1
25:2
30:3
35:4
40:1
45:2
50:3
55:4
