### Mathematical Functions in NumPy  
**Author:** Taskeen Hussain  

### NumPy provides a wide range of mathematical functions for efficient element-wise operations on arrays. These functions enable tasks such as trigonometric calculations, logarithms, and statistical operations, simplifying complex mathematical computations.

In [2]:
# ## Trigonometric Functions


import numpy as np 
a = np.array([0,30,45,60,90]) 

print ('Sine of different angles:') 
# Convert to radians by multiplying with pi/180 
print (np.sin(a*np.pi/180)) 
print ('\n')  

print ('Cosine values for angles in array:') 
print (np.cos(a*np.pi/180)) 
print ('\n')  

print ('Tangent values for given angles:') 
print (np.tan(a*np.pi/180)) 

Sine of different angles:
[0.         0.5        0.70710678 0.8660254  1.        ]


Cosine values for angles in array:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


Tangent values for given angles:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [4]:
a = np.array([0,30,45,60,90]) 

print ('Array containing sine values:') 
sin = np.sin(a*np.pi/180)
print (sin) 
print ('\n')  

Array containing sine values:
[0.         0.5        0.70710678 0.8660254  1.        ]




In [5]:
print ('Compute sine inverse of angles. Returned values are in radians.') 
inv = np.arcsin(sin) 
print (inv) 
print ('\n')  

Compute sine inverse of angles. Returned values are in radians.
[0.         0.52359878 0.78539816 1.04719755 1.57079633]




In [6]:
print ('Check result by converting to degrees:') 
print (np.degrees(inv)) 
print ('\n')  

Check result by converting to degrees:
[ 0. 30. 45. 60. 90.]




In [7]:
print ('arccos and arctan functions behave similarly:') 
cos = np.cos(a*np.pi/180) 
print (cos) 
print ('\n')  

arccos and arctan functions behave similarly:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]




In [8]:
print ('Inverse of cos:') 
inv = np.arccos(cos) 
print (inv) 
print ('\n') 

Inverse of cos:
[0.         0.52359878 0.78539816 1.04719755 1.57079633]




In [9]:
print ('In degrees:') 
print (np.degrees(inv)) 
print ('\n')  

In degrees:
[ 0. 30. 45. 60. 90.]




In [10]:
print ('Tan function:') 
tan = np.tan(a*np.pi/180) 
print (tan)
print ('\n')  

Tan function:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]




In [11]:
print ('Inverse of tan:') 
inv = np.arctan(tan) 
print (inv) 
print ('\n')  

Inverse of tan:
[0.         0.52359878 0.78539816 1.04719755 1.57079633]




In [12]:

print ('In degrees:') 
print (np.degrees(inv))

In degrees:
[ 0. 30. 45. 60. 90.]


In [13]:
# ### Functions for Rounding

import numpy as np 
a = np.array([1.0,5.55, 123, 0.567, 25.532]) 

print ('Original array:') 
print (a) 
print ('\n')  

Original array:
[  1.      5.55  123.      0.567  25.532]




In [14]:
print ('After rounding:') 
print (np.around(a)) 
print (np.around(a, decimals = 1)) 
print (np.around(a, decimals = -1))

After rounding:
[  1.   6. 123.   1.  26.]
[  1.    5.6 123.    0.6  25.5]
[  0.  10. 120.   0.  30.]


In [15]:
a = np.array([-1.7, 1.5, -0.2, 0.6, 10]) 

print ('The given array:') 
print (a) 
print ('\n')  

print ('The modified array:') 
print (np.floor(a))

The given array:
[-1.7  1.5 -0.2  0.6 10. ]


The modified array:
[-2.  1. -1.  0. 10.]


In [16]:
a = np.array([-1.7, 1.5, -0.2, 0.6, 10]) 

print ('The given array:') 
print (a) 
print ('\n')  

print ('The modified array:') 
print (np.ceil(a))

The given array:
[-1.7  1.5 -0.2  0.6 10. ]


The modified array:
[-1.  2. -0.  1. 10.]
