### Arithmetic Operations in NumPy  
**Author:** Taskeen Hussain  

### Arithmetic operations in NumPy enable element-wise operations on arrays, such as addition, subtraction, multiplication, and division. These operations are optimized for high performance and allow efficient numerical calculations on large datasets.

In [7]:
import numpy as np 
# a = np.arange(9, dtype = np.float64).reshape(3,3) 
a = np.arange(9, dtype = np.float32).reshape(3,3) 

print ('First array:') 
print (a) 
print ('\n')  

First array:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]




In [8]:
print ('Second array:') 
b = np.array([10,10,10]) 
print (b) 
print ('\n')

Second array:
[10 10 10]




In [9]:
print ('Add the two arrays:') 
print (np.add(a,b)) 
print ('\n')

Add the two arrays:
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]




In [10]:
print ('Subtract the two arrays:') 
print (np.subtract(a,b)) 
print ('\n')

Subtract the two arrays:
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]




In [11]:
print ('Multiply the two arrays:') 
print (np.multiply(a,b)) 
print ('\n')

Multiply the two arrays:
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]




In [12]:
print ('Divide the two arrays:') 
print (np.divide(a,b))

Divide the two arrays:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


In [13]:
a = np.array([0.25, 1.33, 1, 0, 100]) 

print ('Our array is:') 
print (a) 
print ('\)n')

Our array is:
[  0.25   1.33   1.     0.   100.  ]
\)n


<>:5: SyntaxWarning: invalid escape sequence '\)'
<>:5: SyntaxWarning: invalid escape sequence '\)'
C:\Users\ALR\AppData\Local\Temp\ipykernel_18512\3121098866.py:5: SyntaxWarning: invalid escape sequence '\)'
  print ('\)n')


In [14]:
print ('After applying reciprocal function:') 
print (np.reciprocal(a)) 
print ('\n')  

After applying reciprocal function:
[4.        0.7518797 1.              inf 0.01     ]




C:\Users\ALR\AppData\Local\Temp\ipykernel_18512\4153052681.py:2: RuntimeWarning: divide by zero encountered in reciprocal
  print (np.reciprocal(a))


In [15]:
b = np.array([100], dtype = int) 
print ('The second array is:') 
print (b) 
print ('\n')  

The second array is:
[100]




In [16]:
a = np.array([10,100,1000]) 

print ('Our array is:') 
print (a) 
print ('\n')  

Our array is:
[  10  100 1000]




In [17]:
print ('After applying reciprocal function:') 
print (np.reciprocal(b))

After applying reciprocal function:
[0]


In [18]:
# ### numpy.power()

import numpy as np 

print ('Applying power function:') 
print (np.power(a,2)) 
print ('\n')

Applying power function:
[    100   10000 1000000]




In [19]:
print ('Second array:') 
b = np.array([1,2,3]) 
print (b) 
print ('\n')

Second array:
[1 2 3]




In [20]:
print ('Applying power function again:') 
print (np.power(a,b))

Applying power function again:
[        10      10000 1000000000]


In [22]:
a = np.array([10,20,30]) 
b = np.array([3,5,7])
print ('First array:') 
print (a) 
print ('\n')

First array:
[10 20 30]




In [23]:
print ('Second array:') 
print (b) 
print ('\n')

Second array:
[3 5 7]




In [24]:
print ('Applying mod() function:') 
print (np.mod(a,b)) 
print ('\n')

Applying mod() function:
[1 0 2]




In [25]:
print ('Applying remainder() function:') 
print (np.remainder(a,b)) 

Applying remainder() function:
[1 0 2]


In [26]:
a = np.array([-5.6j, 0.2j, 11. , 1+1j]) 

print ('Our array is:') 
print (a) 
print ('\n')

Our array is:
[-0.-5.6j  0.+0.2j 11.+0.j   1.+1.j ]




In [27]:
print ('Applying real() function:') 
print (np.real(a)) 
print ('\n')

Applying real() function:
[-0.  0. 11.  1.]




In [28]:
print ('Applying imag() function:') 
print (np.imag(a)) 
print ('\n')

Applying imag() function:
[-5.6  0.2  0.   1. ]




In [29]:
print ('Applying conj() function:') 
print (np.conj(a)) 
print ('\n')

Applying conj() function:
[-0.+5.6j  0.-0.2j 11.-0.j   1.-1.j ]




In [30]:
print ('Applying angle() function:') 
print (np.angle(a)) 
print ('\n')  

print ('Applying angle() function again (result in degrees)') 
print (np.angle(a, deg = True))

Applying angle() function:
[-1.57079633  1.57079633  0.          0.78539816]


Applying angle() function again (result in degrees)
[-90.  90.   0.  45.]
