### 2.9 - Statistical Functions in NumPy  
**Author:** Taskeen Hussain  

### NumPy provides a wide range of statistical functions to perform calculations such as mean, median, standard deviation, and correlation. These functions help summarize and analyze data efficiently for scientific and data analysis tasks.

In [2]:
import numpy as np 
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 

print ('Our array is:') 
print (a)  
print ('\n')  

Our array is:
[[3 7 5]
 [8 4 3]
 [2 4 9]]




In [3]:
print ('Applying amin() function:') 
print (np.amin(a,1)) 
print ('\n')

Applying amin() function:
[3 3 2]




In [5]:
print ('Applying amin() function again:') 
print (np.amin(a,0)) 
print ('\n')  

Applying amin() function again:
[2 4 3]




In [4]:
print ('Applying amax() function:') 
print (np.amax(a)) 
print ('\n') 

Applying amax() function:
9




In [6]:
print ('Applying amax() function:') 
print (np.amax(a)) 
print ('\n')

Applying amax() function:
9




In [7]:
print ('Applying amax() function again:') 
print (np.amax(a, axis = 0))

Applying amax() function again:
[8 7 9]


In [8]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 

print ('Our array is:') 
print (a) 
print ('\n')

Our array is:
[[3 7 5]
 [8 4 3]
 [2 4 9]]




In [9]:
print ('Applying ptp() function:') 
print (np.ptp(a)) 
print ('\n')

Applying ptp() function:
7




In [10]:
print ('Applying ptp() function along axis 1:') 
print (np.ptp(a, axis = 1)) 
print ('\n')

Applying ptp() function along axis 1:
[4 5 7]




In [11]:
print ('Applying ptp() function along axis 0:')
print (np.ptp(a, axis = 0))

Applying ptp() function along axis 0:
[6 3 6]


In [14]:
# ### numpy.percentile()
a = np.array([[30,40,70],[80,20,10],[50,90,60]]) 

print ('Our array is:') 
print (a) 
print ('\n')

Our array is:
[[30 40 70]
 [80 20 10]
 [50 90 60]]




In [15]:
print ('Applying percentile() function:') 
print (np.percentile(a,50)) 
print ('\n')

Applying percentile() function:
50.0




In [16]:
print ('Applying percentile() function along axis 1:') 
print (np.percentile(a,50, axis = 1)) 
print ('\n')

Applying percentile() function along axis 1:
[40. 20. 60.]




In [17]:
print ('Applying percentile() function along axis 0:') 
print (np.percentile(a,50, axis = 0))

Applying percentile() function along axis 0:
[50. 40. 60.]


In [18]:
a = np.array([[30,65,70],[80,95,10],[50,90,60]]) 

print ('Our array is:') 
print (a) 
print ('\n')

Our array is:
[[30 65 70]
 [80 95 10]
 [50 90 60]]




In [19]:
print ('Applying median() function:') 
print (np.median(a)) 
print ('\n')

Applying median() function:
65.0




In [20]:
print ('Applying median() function along axis 0:') 
print (np.median(a, axis = 0)) 
print ('\n')

Applying median() function along axis 0:
[50. 90. 60.]




In [21]:
print ('Applying median() function along axis 1:') 
print (np.median(a, axis = 1))

Applying median() function along axis 1:
[65. 80. 60.]


In [22]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print ('Our array is:') 
print (a) 
print ('\n')

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]




In [23]:
print ('Applying mean() function:') 
print (np.mean(a)) 
print ('\n')

Applying mean() function:
3.6666666666666665




In [24]:
print ('Applying mean() function along axis 0:') 
print (np.mean(a, axis = 0)) 
print ('\n')  

print ('Applying mean() function along axis 1:') 
print (np.mean(a, axis = 1))

Applying mean() function along axis 0:
[2.66666667 3.66666667 4.66666667]


Applying mean() function along axis 1:
[2. 4. 5.]


In [25]:
### numpy.average()

import numpy as np 
a = np.array([1,2,3,4]) 

print ('Our array is:') 
print (a) 
print ('\n')

Our array is:
[1 2 3 4]




In [26]:
print ('Applying average() function:') 
print (np.average(a)) 
print ('\n')

Applying average() function:
2.5




In [27]:
# this is same as mean when weight is not specified 
wts = np.array([4,3,2,1]) 

print ('Applying average() function again:') 
print (np.average(a,weights = wts)) 
print ('\n')

Applying average() function again:
2.0




In [28]:
# Returns the sum of weights, if the returned parameter is set to True. 
print ('Sum of weights') 
print (np.average([1,2,3, 4],weights = [4,3,2,1], returned = True))

Sum of weights
(np.float64(2.0), np.float64(10.0))


In [29]:
a = np.arange(6).reshape(3,2) 

print ('Our array is:') 
print (a) 
print ('\n')

Our array is:
[[0 1]
 [2 3]
 [4 5]]




In [30]:
print ('Modified array:') 
wt = np.array([3,5]) 
print (np.average(a, axis = 1, weights = wt)) 
print ('\n')

Modified array:
[0.625 2.625 4.625]




In [31]:
print ('Modified array:') 
print (np.average(a, axis = 1, weights = wt, returned = True))

Modified array:
(array([0.625, 2.625, 4.625]), array([8., 8., 8.]))


In [34]:
print (np.std([1,2,3,4]))

1.118033988749895


In [33]:
print (np.var([1,2,3,4]))


1.25
