# Data_Analysis_with_Numpy
### Author : Taskeen_Hussain
### Date   : 2025-01-04
### Description : This script is used to perform data analysis with numpy library.


In [9]:
# Excercise 1
import numpy as np  
a = np.array([11,20,33]) 
print (a)

[11 20 33]


In [10]:
# Excercise 2
# more_than one dimensional array
import numpy as np 
a = np.array([[12, 23], [34, 45]]) 
print (a)

[[12 23]
 [34 45]]


In [27]:
# Excercise 3
# dimension of the array
import numpy as np 
a = np.array([10, 20, 30,40,50], ndmin = 2) 
print (a)

[[10 20 30 40 50]]


In [34]:
# Excercise 4
# parametrizing the data type 
import numpy as np 
a = np.array([9,10,11], dtype= complex)
print (a)

[ 9.+0.j 10.+0.j 11.+0.j]


In [15]:
# Excercise 5
# parametrizing the data type 
import numpy as np 
# a = np.array([9,10,11], dtype = float)
#a = np.array([9,10,11], dtype = int)
#a = np.array([9,10,11], dtype = str)
a = np.array([9,10,11], dtype = bool)
print (a)

[ True  True  True]


In [38]:
# Excercise 6
# use of scalar array type  
import numpy as np
dt = np.dtype(np.int32) 
dt = np.dtype(np.int64) 
print (dt)

int64


In [43]:
# Excercise 7
# No need to import numpy as np in every line
#int8, int16, int32, int 64, uint8, uint16, uint32, uint64,
# float16, float32, float64 and float128 are the data types in numpy 
#dt = np.dtype('i4')
#dt = np.dtype('uint64')
dt = np.dtype('float64')
print (dt)

float64


In [60]:
# Excercise 8
dt = np.dtype('i1')
print (dt)

int8


In [62]:
# Excercise 9
dt = np.dtype('>i2')
print (dt)

>i2


In [63]:
# Excercise 10
# create a structure data type
dt = np.dtype([('age',np.int64)]) 
print (dt)

[('age', '<i8')]


In [64]:
# Excercise 11
# apply it to ndarray object
dt = np.dtype([('age',np.int8)])
a = np.array([(30,),(40,),(50,)], dtype = dt) 
print (a)

[(30,) (40,) (50,)]


In [65]:
# Excercise 12
# name of file is used to access content of age column
dt = np.dtype([('age',np.int8)]) 
a = np.array([(50,),(50,),(20,)], dtype = dt) 
print (a['age'])

[50 50 20]


In [67]:
# Excercise 13
alumni  = np.dtype([('name','S30'), ('age', 'i2'), ('marks', 'f2')])
print (alumni)

[('name', 'S30'), ('age', '<i2'), ('marks', '<f2')]


In [70]:
# Excercise 14
alumni = np.dtype([('name','S30'), ('age', 'i2'), ('marks', 'f4')]) 
a = np.array([('xyz', 31, 40),('xyz', 28, 65)], dtype = alumni) 
print (a)

[(b'xyz', 31, 40.) (b'xyz', 28, 65.)]
