# "Sorting Arrays Efficiently with NumPy"
## Author: Taskeen Hussain
## Date: 2025-01-05
### Learn how to sort arrays efficiently using NumPy, a powerful library for numerical computing in Python. Explore various sorting techniques to organize data for analysis and computation.

In [13]:
# Excercise for numpy sorting practice it for learn numpy data structure and sorting
import numpy as np  
a = np.array([[33,57],[92,19]]) 

print ('Our array is:') 
print (a) 
print ('\n')

Our array is:
[[33 57]
 [92 19]]




In [14]:

print ('Applying sort() function:') 
print (np.sort(a)) 
print ('\n') 


Applying sort() function:
[[33 57]
 [19 92]]




In [15]:
print ('Sort along axis 0:') 
print (np.sort(a, axis = 0)) 
print ('\n')  


Sort along axis 0:
[[33 19]
 [92 57]]




In [17]:
# Order parameter in sort function 
dt = (np.dtype([('name', 'S20'),('age', int)])) 
a = (np.array([("Ali",21),("Malik",25),("Niaz", 17), ("amar",27)], dtype = dt)) 


In [18]:
print ('Our array is:') 
print (a) 
print ('\n')  

Our array is:
[(b'Ali', 21) (b'Malik', 25) (b'Niaz', 17) (b'amar', 27)]




In [19]:
print ('Order by name:') 
print (np.sort(a, order = 'name'))

Order by name:
[(b'Ali', 21) (b'Malik', 25) (b'Niaz', 17) (b'amar', 27)]


In [20]:
x = np.array([3, 1, 2]) 

print ('Our array is:') 
print (x) 
print ('\n')

Our array is:
[3 1 2]




In [21]:
print ('Applying argsort() to x:') 
y = np.argsort(x) 
print (y) 
print ('\n') 

Applying argsort() to x:
[1 2 0]




In [22]:
print ('Reconstruct original array in sorted order:') 
print (x[y]) 
print ('\n')

Reconstruct original array in sorted order:
[1 2 3]




In [23]:
print ('Reconstruct the original array using loop:') 
for i in y: 
   print (x[i])

Reconstruct the original array using loop:
1
2
3


In [25]:
nm = ('Ali','Malik','Niaz','amar') 
dv = ('f.y.', 's.y.', 's.y.', 'f.y.') 
ind = np.lexsort((dv,nm)) 


In [26]:
print ('Applying lexsort() function:') 
print (ind) 
print ('\n')

Applying lexsort() function:
[0 1 2 3]




In [27]:
print ('Use this index to get sorted data:') 
print ([nm[i] + ", " + dv[i] for i in ind]) 

Use this index to get sorted data:
['Ali, f.y.', 'Malik, s.y.', 'Niaz, s.y.', 'amar, f.y.']


In [28]:
a = np.array([[30,40,70],[80,20,10],[50,90,60]]) 

print ('Our array is:') 
print (a) 
print ('\n') 

Our array is:
[[30 40 70]
 [80 20 10]
 [50 90 60]]




In [29]:
print ('Applying argmax() function:') 
print (np.argmax(a)) 
print ('\n')  


Applying argmax() function:
7




In [30]:
print ('Index of maximum number in flattened array')
print (a.flatten()) 
print ('\n')  

Index of maximum number in flattened array
[30 40 70 80 20 10 50 90 60]




In [31]:
print ('Array containing indices of maximum along axis 0:') 
maxindex = np.argmax(a, axis = 0) 
print (maxindex) 
print ('\n')  


Array containing indices of maximum along axis 0:
[1 2 0]




In [32]:
print ('Array containing indices of maximum along axis 1:') 
maxindex = np.argmax(a, axis = 1) 
print (maxindex) 
print ('\n') 

Array containing indices of maximum along axis 1:
[2 0 1]




In [33]:
print ('Applying argmin() function:') 
minindex = np.argmin(a) 
print (minindex) 
print ('\n')  


Applying argmin() function:
5




In [34]:
print ('Flattened array:') 
print (a.flatten()[minindex]) 
print ('\n')  


Flattened array:
10




In [35]:
print ('Flattened array along axis 0:') 
minindex = np.argmin(a, axis = 0) 
print (minindex)
print ('\n')

Flattened array along axis 0:
[0 1 1]




In [36]:
print ('Flattened array along axis 1:') 
minindex = np.argmin(a, axis = 1) 
print (minindex)


Flattened array along axis 1:
[0 2 0]


In [37]:
a = np.array([[30,40,0],[0,20,10],[50,0,60]]) 

print ('Our array is:') 
print (a) 
print ('\n')  

Our array is:
[[30 40  0]
 [ 0 20 10]
 [50  0 60]]




In [38]:
print ('Applying nonzero() function:') 
print (np.nonzero (a))

Applying nonzero() function:
(array([0, 0, 1, 1, 2, 2]), array([0, 1, 1, 2, 0, 2]))


In [39]:
x = np.arange(9.).reshape(3, 3) 

print ('Our array is:') 
print (x)

Our array is:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [40]:
print ('Indices of elements > 3') 
y = np.where(x > 3) 
print (y)

Indices of elements > 3
(array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2]))


In [41]:
print ('Use these indices to get elements satisfying the condition') 
print (x[y])

Use these indices to get elements satisfying the condition
[4. 5. 6. 7. 8.]


In [42]:
x = np.arange(9.).reshape(3, 3) 

print ('Our array is:') 
print (x)

Our array is:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [43]:
# define a condition 
condition = np.mod(x,2) == 0 

In [44]:
print ('Element-wise value of condition') 
print (condition)  

Element-wise value of condition
[[ True False  True]
 [False  True False]
 [ True False  True]]


In [45]:
print ('Extract elements using condition') 
print (np.extract(condition, x))

Extract elements using condition
[0. 2. 4. 6. 8.]
